export default function apiHeader() {
  
     return { authorization: 'Bearer  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImMxN2ZmZTBkLTVmNzAtNGU1MS1iNDkyLTkyMTdmN2MxYjgzZCIsImlhdCI6MTYxOTU2MjcwNSwic3ViIjoiZGV2ZWxvcGVyLzEzN2FlOTA0LThiODctYzIzOC1mM2Q3LTYwMGQ0ZDc3YjM0OSIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI5NS4xMi4xMTMuMTk4Il0sInR5cGUiOiJjbGllbnQifV19.wDmlwFxKDRoQjwvVrBeF7U2X0Xh_oOvmUifOVgW6wSNHZYVssRRrgqg04Uldy7gswhbXita22wuzmaKfkguNgw','Accept': 'application/json'}
    
}
