var routes = [
  {
    path: "/profile",
    layout: "/panel",
    name: "Profile",
    icon: "nc-icon nc-circle-09",
    component: "Profile",
    show: false,
  },
  {
    path: "/adminusers",
    layout: "/panel",
    name: "AdminUsers",
    icon: "nc-icon nc-circle-09",
    component: "Admin",
    show: false,
  },
  {
    path: "/adminevents",
    layout: "/panel",
    name: "AdminEvents",
    icon: "nc-icon nc-circle-09",
    component: "AdminEvents",
    show: false,
  },
  {
    path: "/admincontroller",
    layout: "/panel",
    name: "AdminController",
    icon: "nc-icon nc-circle-09",
    component: "AdminController",
    show: false,
  },
  {
    path: "/create",
    layout: "/panel",
    name: "CreateEvent",
    icon: "nc-icon nc-simple-add",
    component: "CreateMatch",
    show: false,
  },
  {
    path: "/",
    layout: "/user/:username",
    name: "User",
    icon: "nc-icon nc-circle-09",
    component: "User",
    show: false,
  },
  {
    path: "/dashboard",
    layout: "/panel",
    name: "Dashboard",
    icon: "nc-icon nc-chart-pie-35",
    component: "Dashboard",
    show: true,
  },
  {
    path: "/rewards",
    layout: "/panel",
    name: "Rewards",
    icon: "nc-icon nc-notification-70",
    component: "Rewards",
    show: true,
  },
  {
    path: "/mymatches",
    layout: "/panel",
    name: "My Matches",
    icon: "nc-icon nc-controller-modern",
    component: "MyMatches",
    show: false,
  },
  {
    path: "/market",
    layout: "/panel",
    name: "MarketPlace",
    icon: "nc-icon nc-refresh-02",
    component: "Market",
    show: true,
  },
  {
    path: "/cashier",
    layout: "/panel",
    name: "Cashier",
    icon: "nc-icon nc-bank",
    component: "Cashier",
    show: true,
  },
  {
    path: "/create",
    layout: "/panel",
    name: "Create",
    icon: "nc-icon nc-simple-add",
    component: "Create",
    show: false,
  },
  {
    path: "/logut",
    layout: "/panel",
    name: "Logout",
    icon: "nc-icon nc-button-power",
    component: "Logout",
    show: false,
  },

  {
    path: "/",
    layout: "/lobby/:id/:title/:matchid/:matchlevel",

    name: "Match Lobby",
    icon: "nc-icon nc-simple-add",
    component: "LockScreenPage",
    show: false,
  },
  {
    path: "/",
    layout: "/lobby/:id/:title",

    name: "Match Lobby",
    icon: "nc-icon nc-simple-add",
    component: "LockScreenPage",
    show: false,
  },
  {
    path: "/",
    layout: "/matchlobby",
    name: "Match Lobby",
    icon: "nc-icon nc-simple-add",
    component: "LockScreenPage",
    show: false,
  },

  {
    path: "/",
    layout: "/home",
    name: "Home",
    icon: "nc-icon nc-chart-pie-35",
    component: "Landing",
    show: false,
  },
  {
    path: "/",
    layout: "/marketplace",
    name: "MarketPlace",
    icon: "nc-icon nc-chart-pie-35",
    component: "Market",
    show: false,
  },
  {
    path: "/",
    layout: "/games",
    name: "User",
    icon: "nc-icon nc-circle-09",
    component: "Games",
    show: false,
  },
  {
    path: "/",
    layout: "/game/:gamename",
    name: "User",
    icon: "nc-icon nc-circle-09",
    component: "Game",
    show: false,
  },
  {
    path: "/*",
    layout: "/content",
    name: "User",
    icon: "nc-icon nc-circle-09",
    component: "Content",
    show: false,
  },
];
export default routes;
